variable "name" {
  type        = string
  description = "Name of the created Security Group."
  default     = "cloudfront-public-cidrs"
}

variable "vpc_id" {
  type        = string
  description = "VPC to attach security group(s) to."
}
variable "description" {
  type        = string
  description = "Description to attach to security group(s)."
  default     = "Allow inbound traffic from cloudfront (CIDRs autogenerated from https://ip-ranges.amazonaws.com/ip-ranges.json)"
}

variable "tags" {
  description = "Tags to be applied to AWS resources."
  type        = map(string)

  validation {
    condition = alltrue([
      contains(keys(var.tags), "team"),
      contains(keys(var.tags), "service"),
      contains(keys(var.tags), "impact"),
    ])
    error_message = "Required tags are missing! Please provide tags 'team', 'service' and 'impact'."
  }
}
